// The full list of named screens the preview harness can render and
// screenshot. Shared between the drive script (bridge.js) and the shoot
// script (shoot.mjs) so both always agree on what "every screen" means.
export const SCREEN_NAMES = [
  'dashboard',
  'connections',
  'connection-wizard',
  'queue',
  'browse',
  'browse-list',
  'browse-forward-enabled',
  'browse-command-overflow',
  'browse-selection',
  'browse-bulk-bar',
  'browse-clipboard-cut',
  'browse-clipboard-copy',
  'browse-connection-picker-favorites',
  'quick-look',
  'quick-look-crop',
  'quick-look-trim',
  'editor',
  'play',
  'play-covering',
  'play-fullscreen',
  'size',
  'backup',
  'logs',
  'settings',
  'tray',
  'delete-dialog',
  'bulk-delete-dialog',
  'move-picker',
  'favorites-menu',
  'entry-context-menu',
  'properties-dialog',
  'browse-options-popover',
]
